### ISSUE TITLE
Untitled notebook

### ISSUE THREAD

**Issue by jGaboardi** [pysal/tobler#122] opened 2021-01-13 18:26 UTC
There is currently an [Untitled notebook](https://github.com/pysal/tobler/blob/master/notebooks/Untitled.ipynb) in the `master` branch. This should be removed, correct?

**Comment by knaaptime** [comment] 2021-01-13 18:41
yeah i was gonna do that and #121 at the same time, unless you wanna drop it now :)

**Comment by jGaboardi** [comment] 2021-01-13 18:44
> unless you wanna drop it now :)

LOL. Nah, I just saw that and thought to make a note of it!

**Comment by knaaptime** [comment] 2021-01-13 21:15
duplicate of #94

**Closed by knaaptime** 2021-01-13 21:15 UTC
