### ISSUE TITLE
area_interpolate() fills gap areas where target and source geopandas frames don't intersect with 0s instead of NaNs

### ISSUE THREAD

**Issue by 3SMMZRjWgS** [pysal/tobler#217] opened 2024-08-14 06:07 UTC
Hello, 

Thank you so much for making Tobler available. This package appears to fill a critical gap in basic gis operations in Python for a function such as area_interpolate, which is much more accessible in R through a package such as sf.

There's one challenge using the area_interpolate function in Tobler, which is that for gap geometries (where source geometry doesn't cover target geometry), it auto fills them with 0s. While this is okay if the values aren't expected to be 0s, it becomes a challenge if values (i.e. minimum temperature in degree-C) could potentially be 0s. Is there a way to allow such gap geometries to display NaNs instead of 0s?

Thank you!

**Comment by martinfleis** [comment] 2024-08-14 07:17
That is a bug, thanks for pointing it out!

> which is much more accessible in R through a package such as sf.

There's no need for these kinds of comments as they do not help anything, only cause negative emotions. Please accept that the ecosystems are organised differently and that areal interpolation is considered out of scope in geopandas, which would be the Python alternative of sf. You can trust me on that as I'm involved in both tobler and geopandas. If you'd like to enhance the accessibility of the interpolation for geopandas users, there's always an option to open a PR providing better documentation of tools from the rest of the ecosystem, like tobler.

**Comment by martinfleis** [comment] 2024-08-14 07:29
@knaaptime I believe that all this is caused by these replacements

https://github.com/pysal/tobler/blob/915d88285f8427eb359a66e38ee6e92c877f7321/tobler/util/util.py#L48-L71

What would happen if we haven't done those? We would end up with NaN for every geometry that is at least partially covered by the source geom with missing value? That may be more trustworthy result in the end. 

Alternatively, we could try to filter geometries with missing values out and do not consider them at all when doing the dot product, though I am not sure which is preferable.

Replacing missing with 0 seems like something a user should do, rather than we, given the 0 may not be suitable.

**Comment by knaaptime** [comment] 2024-08-16 16:30
fwiw, [`sf` has the same logic](https://r-spatial.github.io/sf/reference/interpolate_aw.html) in the case where the value is null. Not sure what they do in the case where the weight is null, but I'm happy with our current rationale until persuaded differently.

<img width="917" alt="Screenshot 2024-08-16 at 9 26 29 AM" src="https://github.com/user-attachments/assets/ff8d8908-b501-420c-a0ca-e75e1ca35735">

**Closed by knaaptime** 2024-08-16 16:30 UTC

**Comment by bramson** [comment] 2025-09-04 03:26
I was going to write a similar issue/request, but maybe it's enough to write a comment here.
I generally agree with treating NaN as zero for area interpolation when any of the target polygon is covered by values.
What else would make sense?

Well, here's three ideas to consider:

(1) Support a manual override to another value. A `replace_nan_with` or `fillna` argument that uses a different value besides zero for special cases where somebody would want that:  e.g. some data uses -9999 or -8888 instead of Nan, although I think that averaging over that would be even worse, so I'm not sure there even is a reasonable use-case here.  But maybe, for some unusual cases, there is a better value to use than zero as the baseline when data is missing.  Of course, this could be done by users before running the data through this algorithm, so there is no real need to add the feature besides convenience to a small group of hypothetical users.

(2) Support a `remove_nan` argument that removes the rows with NaN values from the source and treats them "out of bounds".  Then the `allocate_total` argument determines whether to treat those overlapping areas as zero or remove them from the calculation.  I think this is generally a good idea, especially for intensive variables.  I would use this option if it existed as this cannot be accomplished effectively in preprocessing because different variables may have NaN in different rows, so the dropping has to be done per variable just before interpolation of that variable.

(3) If **ALL** the source values for a target geometry are NaN (or none or inf), then report NaN (or none or inf instead of 0) for that target. If it is **partially** covered by NaN, then treat that portion as 0 (or ignored if `allocate_total=False`). This would cover the original posters request: if a target polygon has no overlapping polygon in source (or polygons with only NaNs), then the target becomes NaN.  Partial NaN or non-existent overlaps are handled depending on `allocate_total`.  This is what my personal previous areal interpolation algorithm did, but it didn't use numpy for the value allocation (and was MUCH slower).  

I don't know how much demand this is for this, but I expect these are not uncommon use cases.  In my case, I don't want to treat/display areas completely over water as having zero population in the same way that industrial areas have zero population (although I can't say that's wrong either).  

Because I need (3) and want (2), I plan on duplicating the source and handling those cases, but I don't know how easy that will be given the current calculation methods.  In the worse case, I'll improve my old STRtree method with lessons learned from your method that handles NaN in these ways.

**Comment by knaaptime** [comment] 2025-09-04 14:57
thanks for the comment. 1 and 2 i think are super easy pre-processing steps (either fillna or dropna on your source before interpolation), so that's best handled *before* sending the data to the interpolation function, not during the process.

3 doesnt really work because (a) i dont think it's a good idea to treat NaNs contextually instead of universally (sometimes they are 0 other times they aren't) and (b) as i said above, the current implementation using a matrix product will propagate the NaNs, so won't allow 'portioning' like you describe. That said, if you happen to come up with an interesting implementation you'd like to contribute, we'd be happy to take a look :)
